const featured = [
  ["01", "DealerOS", "Dealership CRM and service operations platform MVP.", "LIVE · MVP", "Product · Full Stack", "https://dealeros-mvp.vercel.app/dashboard"],
  ["02", "Econexus", "Commercial economics data and research intelligence platform for institutions, surveys, analytics and monetization.", "LIVE · MVP", "Data · Product", "https://econexus-data-research-platform.vercel.app/"],
  ["03", "EconNext Lagos", "Flagship digital product for NESA Lagos, combining polished UX, responsive architecture, animation and integrations.", "LIVE · PUBLIC", "Frontend · Product", "https://econnext-lagos-platform-version-2.vercel.app/"],
  ["04", "Career Authority Assessment", "Interactive assessment experience for executive presence, visibility, communication, positioning and negotiation.", "LIVE · MVP", "UX · Web App", "https://ornella-career-authority-assessment.vercel.app/"],
  ["05", "MODE", "Creative and technology company website combining editorial direction, brand expression and modern web interaction.", "LIVE · PUBLIC", "Brand · Web", "https://mode-site-alpha.vercel.app/"],
  ["06", "Femi Portfolio", "Personal portfolio system for software engineering, product building and UI/UX work.", "LIVE · PUBLIC", "Next.js · Framer Motion", "https://oluwafemi-ayansola-portfolio-rho.vercel.app/"],
];

const archive = ["LifeSaver MedConnect", "CapitalLink", "Medilens AI", "Digital Fitness Wellness", "Shoppers", "RoomieConnect", "CargoLink", "MODE Store", "LuxeStay", "BuildTrack", "PlayNaija", "TasteNG", "ChopNow", "SwiftLogistics", "TrackNG", "MediCare", "DocBook", "GreenHarvest", "AgroMarket", "NovaBank Dashboard", "PrimeEstate", "PropMarket", "PetroCorp", "PetroOps", "SolarEdge", "SolarQuote"];

export default function Home(){return <main>
  <nav className="nav"><div className="wrap navin"><a className="logo" href="#top">OA.</a><div className="links"><a href="#work">Work</a><a href="#about">About</a><a href="#experience">Experience</a><a href="#stack">Stack</a><a href="#contact">Contact</a></div><div className="status"><i className="dot"/> OPEN TO OPPORTUNITIES</div></div></nav>
  <section className="hero" id="top"><div className="wrap"><div className="eyebrow mono">Lagos, Nigeria · 2026</div><h1>Oluwafemi<br/><span>Ayansola.</span></h1><div className="intro"><p>I build digital products that combine <strong>good engineering, thoughtful design, and real-world problem solving.</strong></p><div><div className="small mono">SOFTWARE ENGINEER<br/>PRODUCT BUILDER<br/>UI/UX DESIGNER</div><div className="photo mono">PHOTO PLACEHOLDER<br/>New professional portrait coming soon.</div></div></div></div></section>
  <section className="section" id="work"><div className="wrap"><div className="sectionhead"><h2>Selected work.</h2><p>Live products and systems I have designed, engineered or contributed to. Each project links directly to its deployed experience.</p></div><div className="projects">{featured.map(([n,t,d,s,m,url])=><a className="project" href={url} target="_blank" rel="noreferrer" key={t}><div className="num mono">{n}</div><div><h3>{t} <span className="arrow">↗</span></h3><p>{d}</p></div><div className="meta mono">{s}<br/><span>{m}</span></div></a>)}</div><div className="archive"><b>More experiments & prototypes</b><br/>{archive.join(" · ")}<br/><span className="small">Prototype / template builds are intentionally presented as works in progress rather than production-ready products.</span></div></div></section>
  <section className="section" id="about"><div className="wrap"><div className="sectionhead"><h2>About.</h2><p>Designer instincts. Engineering discipline. Entrepreneurial curiosity.</p></div><div className="aboutgrid"><div><p>My path has moved from business and marketing into product design, frontend development and software engineering. Today I study Computer Science alongside Economics while building practical digital products.</p><p>I care about the whole product: discovering the problem, shaping the experience, engineering the system and getting it into users' hands.</p></div><div><div className="small mono">NOW EXPLORING</div><p>AI & data products<br/>Fintech & commerce<br/>Economic intelligence<br/>Product strategy<br/>Human-centered interfaces</p></div></div></div></section>
  <section className="section" id="experience"><div className="wrap"><div className="sectionhead"><h2>Experience.</h2></div><div className="timeline"><div className="row"><div className="date mono">2022 — NOW</div><div><h3>M.O.D.E · Full Stack Developer</h3><p>Python, Django, SQL, CMS development, code reviews and agile delivery.</p></div><div className="place mono">LAGOS</div></div><div className="row"><div className="date mono">2026</div><div><h3>EconNext Lagos · Frontend Developer</h3><p>React, Vite, Tailwind and deployment workflows for a conference product.</p></div><div className="place mono">LAGOS</div></div><div className="row"><div className="date mono">2025</div><div><h3>Caleb GDG · Mobile Developer</h3><p>React Native accommodation product with graph-based room matching concepts.</p></div><div className="place mono">LAGOS</div></div><div className="row"><div className="date mono">2021 — NOW</div><div><h3>Freelance · UI/UX Designer</h3><p>Product design, research, prototyping and frontend collaboration for global clients.</p></div><div className="place mono">REMOTE</div></div></div></div></section>
  <section className="section" id="stack"><div className="wrap"><div className="sectionhead"><h2>Stack.</h2><p>A practical toolkit spanning product discovery, interface design, software engineering and deployment.</p></div><div className="stack"><div className="skill"><b>FRONTEND</b><div>React · Next.js · TypeScript · JavaScript · Tailwind · HTML · CSS</div></div><div className="skill"><b>BACKEND</b><div>Python · Django · Node.js · REST APIs · SQL · PostgreSQL</div></div><div className="skill"><b>PRODUCT & UX</b><div>Figma · UI/UX · User Research · Prototyping · User Flows · Testing</div></div><div className="skill"><b>ENGINEERING</b><div>Git · Docker · Vercel · Agile/Scrum · Software Architecture</div></div><div className="skill"><b>MOBILE</b><div>React Native · Mobile Application Development</div></div><div className="skill"><b>DATA & AI</b><div>Data products · Analytics · AI product concepts · Economic intelligence</div></div><div className="skill"><b>LANGUAGES</b><div>Python · JavaScript · TypeScript · Java · Swift · PHP · SQL</div></div><div className="skill"><b>DESIGN</b><div>Figma · Adobe XD · Sketch · InVision · Behance</div></div></div></div></section>
  <section className="section" id="contact"><div className="wrap"><div className="contact"><div><div className="eyebrow mono">Have a problem worth solving?</div><h2>Let's build<br/>something.</h2></div><div><p>For software engineering, product design, collaboration or ambitious digital products, reach out.</p><a href="mailto:ayansolaoluwafemi62@gmail.com">ayansolaoluwafemi62@gmail.com ↗</a><a href="https://github.com/OluwafemiAyansola62" target="_blank">GitHub ↗</a><a href="https://www.linkedin.com/in/oluwafemi-ayansola-7b005b1b2/" target="_blank">LinkedIn ↗</a><a href="https://www.behance.net/ayansola" target="_blank">Behance ↗</a></div></div></div></section>
  <footer className="wrap footer"><span>© 2026 Oluwafemi Ayansola</span><span className="mono">PERSONAL WEBSITE · URL TBC</span></footer>
</main>}
